### PR TITLE
Make api url configurable

### LINKED ISSUE #12: No support for "non-minecraft" CurseForge sites
Hi, I'm using this plugin in a multi-version spanning Minecraft mod, that also has a Bukkit version.

The bukkit version doesn't upload correctly because the API's base URL is `dev.bukkit.org` instead of `minecraft.curseforge.com`.
If this was made settable, it would allow not only bukkit plugins, but also all other sites, such as Terraria, KSP and others.

Please consider adding support,
Thanks in advance,
Dries

### PR DESCRIPTION
**Pull request by dshadowwolf**
This adds "project.apiUrl" to configure the Curse API end-points domain, making CurseGradle capable of uploading for non-Forge mods. Should resolve #12 (originally added it to project.ext - was pointed out that it should be in the "project" closure in the "curseforge" block instead, so changed it)

### CODE REVIEW

**Comment by HeroCC** [comment]
Would you mind updating the README.md so other users can see this functionality? And @matthewprenger, have you had a chance to look at this?

**Comment by Darkhax** [comment]
This PR has a few issues related to versions. 
- In the error message when no version is specified it asks for the Minecraft version instead of the game version. This should be changed to game-neutral language. 
- Valid versions list seems to be empty for other games, haven't tested with Minecraft itself yet. `1.3.29 is not a valid game version. Valid versions are: []` for `https://stardewvalley.curseforge.com`. Calling the versions endpoint manually does return a proper versions list.

**Comment by matthewprenger** [comment]
Haven't had a chance to do much development in recent months, but what darkhax pointed out doesn't surprise me. This project was written around Minecraft and the more I think about it, won't simply work with other projects by just changing the base URL.

I'm not familiar with the other games that CurseForge supports, so I wouldn't be able to speak with any knowledge on how integration with them should look. Each game likely has its own quirks around versions/dependencies that would need to be dealt with on a case-by-case basis.

I'm going to go ahead and close this one since just changing the base URL won't be enough.

**Comment by Darkhax** [comment]
@matthewprenger I think you have come to the wrong conclusion here. From my own analysis of the various APIs, they are almost entirely the same. Currently Minecraft and Bukkit sites are the only ones with additional properties. For example, StardewValley has the exact same versions end point as Minecraft, so that issue is elsewhere in the gradle plugin. 

As for all of the other edge cases that currently exist (Java version), and future properties that may exist, the file metadata is just a json string. At the very least, that json string could be exposed and modified by the build script to support new properties in the future.

**Pull request closed without merging**
