### PR TITLE
Add CurseProject return to the project function

### PR DESCRIPTION
**Pull request by TheTemportalist**
Allows plugins to use the project created

### CODE REVIEW

**Comment by AbrarSyed** [comment]
hey mathew, why arnt you going all the way and just doing a DSLObjectCOntainer?

**Comment by TheTemportalist** [comment]
All the sudden a spontaneous @AbrarSyed appears 0_0

**Comment by AbrarSyed** [comment]
behold, the power of notification emails

**Comment by TheTemportalist** [comment]
I specifically want to use this functionality for https://github.com/TheTemportalist/AutomataGradlePlugin/blob/master/src/main/groovy/temportalist/automata/ExtensionAutomata.groovy#L192

**Comment by AbrarSyed** [comment]
uh.. it dont work like that.. last I checked thats impossible, even with
the awesome power of groovy...

Now it CAN be done, just not the way you are doing it..

**Comment by TheTemportalist** [comment]
Hmmm, debatable. Nothing has broken yet haha

**Comment by TheTemportalist** [comment]
@AbrarSyed If you want to give me pointers to better practices, instead of just "that's impossible", I would welcome them.

**Pull request closed without merging**
